theme: jekyll-theme-slate
title: The homepage of Bruno Kowalik
description: What you will find here are links to projects, publications, and repositories related to the former.
plugins:
  - jemoji
url: "https://brunojestem.github.io/"
markdown: kramdown
